### ISSUE TITLE
["Logging" tab] :: [Pre-filter] :: "NullPointerException" after "Save" button is pressed

### ISSUE THREAD

**Issue by alena-bobryk** [alshpak/kafka_data_viewer#2]
**The error:**
Next records attemptio.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | null

        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
        at io.reactivex.subjects.PublishSubject$PublishDisposable.onError(PublishSubject.java:316)
        at io.reactivex.subjects.PublishSubject.onError(PublishSubject.java:243)
        at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
        at io.reactivex.internal.observers.BasicFuseableObserver.fail(BasicFuseableObserver.java:110)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
        at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:308)
        at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:228)
        at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at java.lang.String.<init>(Unknown Source)
        at devtools.kafka_data_viewer.kafkaconn.StringMessageFormat$.decode(MessageFormats.scala:55)
        at devtools.kafka_data_viewer.ui.DecodingFunction$.decode(KafkaTopicInfoPanes.scala:50)
        at devtools.kafka_data_viewer.ui.RecordsOutputTablePane.$anonfun$new$3(KafkaTopicInfoPanes.scala:73)
        at scala.collection.immutable.Stream.map(Stream.scala:418)
        at devtools.lib.rxext.LoggableOps$AppendLogOp.map(rxext.scala:92)
        at devtools.kafka_data_viewer.ui.RecordsOutputTablePane.$anonfun$new$2(KafkaTopicInfoPanes.scala:73)
        at devtools.lib.rxext.Observable.$anonfun$map$1(rxwrapper.scala:18)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:57)
        ... 13 more
Exception in thread "JavaFX Application Thread" io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | null
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
        at io.reactivex.subjects.PublishSubject$PublishDisposable.onError(PublishSubject.java:316)
        at io.reactivex.subjects.PublishSubject.onError(PublishSubject.java:243)
        at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
        at io.reactivex.internal.observers.BasicFuseableObserver.fail(BasicFuseableObserver.java:110)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
        at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:308)
        at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:228)
        at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)Next records attempt

        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at java.lang.String.<init>(Unknown Source)
        at devtools.kafka_data_viewer.kafkaconn.StringMessageFormat$.decode(MessageFormats.scala:55)
        at devtools.kafka_data_viewer.ui.DecodingFunction$.decode(KafkaTopicInfoPanes.scala:50)
        at devtools.kafka_data_viewer.ui.RecordsOutputTablePane.$anonfun$new$3(KafkaTopicInfoPanes.scala:73)
        at scala.collection.immutable.Stream.map(Stream.scala:418)
        at devtools.lib.rxext.LoggableOps$AppendLogOp.map(rxext.scala:92)
        at devtools.kafka_data_viewer.ui.RecordsOutputTablePane.$anonfun$new$2(KafkaTopicInfoPanes.scala:73)
        at devtools.lib.rxext.Observable.$anonfun$map$1(rxwrapper.scala:18)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:57)
        ... 13 more

**Comment by alshpak** [comment]
fixed in 0.1
